export const toptreding = [
    {
        id:1,
        Product_Name:"Tops",
        Product_Type:"Earrings",
        Brand_Name:"Chand Bali",
        Product_Code:"SSJCB10011",
        Availability:"in stock",
        Product_Metal:"SILVER",
        Product_Purity:"92.5",
        Product_Color:"GOLD",
        Product_Weigth:"19.384 Grams",
        Certified_By:"BIS Hallmark",
        View:"1"
    },
    {
        id:2,
        Product_Name:"Tops",
        Product_Type:"Earrings",
        Brand_Name:"Chand Bali",
        Product_Code:"SSJCB10011",
        Availability:"in stock",
        Product_Metal:"SILVER",
        Product_Purity:"92.5",
        Product_Color:"GOLD",
        Product_Weigth:"19.384 Grams",
        Certified_By:"BIS Hallmark",
        View:"1"
    },
    {
        id:3,
        Product_Name:"Tops",
        Product_Type:"Earrings",
        Brand_Name:"Chand Bali",
        Product_Code:"SSJCB10011",
        Availability:"in stock",
        Product_Metal:"SILVER",
        Product_Purity:"92.5",
        Product_Color:"GOLD",
        Product_Weigth:"19.384 Grams",
        Certified_By:"BIS Hallmark",
        View:"1"
    },
    {
        id:4,
        Product_Name:"Tops",
        Product_Type:"Earrings",
        Brand_Name:"Chand Bali",
        Product_Code:"SSJCB10011",
        Availability:"in stock",
        Product_Metal:"SILVER",
        Product_Purity:"92.5",
        Product_Color:"GOLD",
        Product_Weigth:"19.384",
        Certified_By:"BIS Hallmark",
        View:"1"
    },
    {
        id:5,
        Product_Name:"Tops",
        Product_Type:"Earrings",
        Brand_Name:"Chand Bali",
        Product_Code:"SSJCB10011",
        Availability:"in stock",
        Product_Metal:"SILVER",
        Product_Purity:"92.5",
        Product_Color:"GOLD",
        Product_Weigth:"19.384 Grams",
        Certified_By:"BIS Hallmark",
        View:"1"
    },
    {
        id:6,
        Product_Name:"Tops",
        Product_Type:"Earrings",
        Brand_Name:"Chand Bali",
        Product_Code:"SSJCB10011",
        Availability:"in stock",
        Product_Metal:"SILVER",
        Product_Purity:"92.5",
        Product_Color:"GOLD",
        Product_Weigth:"19.384 Grams",
        Certified_By:"BIS Hallmark",
        View:"1"
    },
    {
        id:7,
        Product_Name:"Tops",
        Product_Type:"Earrings",
        Brand_Name:"Chand Bali",
        Product_Code:"SSJCB10011",
        Availability:"in stock",
        Product_Metal:"SILVER",
        Product_Purity:"92.5",
        Product_Color:"GOLD",
        Product_Weigth:"19.384 Grams",
        Certified_By:"BIS Hallmark",
        View:"1"
    },
    {
        id:8,
        Product_Name:"Tops",
        Product_Type:"Earrings",
        Brand_Name:"Chand Bali",
        Product_Code:"SSJCB10011",
        Availability:"in stock",
        Product_Metal:"SILVER",
        Product_Purity:"92.5",
        Product_Color:"GOLD",
        Product_Weigth:"19.384",
        Certified_By:"BIS Hallmark",
        View:"1"
    },
]
